### PR TITLE
fix: Text file busy error caused by racy downloads

### LINKED ISSUE #12: Running the hook for multiple files causes an issue when downloading the binary for the first time
```
buildifier...............................................................Failed

- hook id: buildifier

- exit code: 126



/root/.cache/pre-commit/repo1ap53cxa/buildifier-wrapper.sh: line 53: /root/.cache/pre-commit/buildifier/linux-amd64-6.0.0/buildifier/buildifier-fix: Text file busy

mv: cannot create regular file '/root/.cache/pre-commit/buildifier/linux-amd64-6.0.0/buildifier/buildifier-fix': File exists
```

It is critical when running it in CI, for example, in Jenkins.

The command line I used.
```
pre-commit run --all-files
```

### PR DESCRIPTION
**Pull request by Blaok**
Fixes #12.

### CODE REVIEW

File: buildifier-wrapper.sh [hunk 1]
```diff
@@ -56,15 +58,9 @@ fi
...
-  # Protect against races of concurrent hooks downloading the same binary
-  if [[ ! -x "$binary" ]]; then
-    mv "$tmp_binary" "$binary"
-  fi
-
+  mv "$tmp_binary" "$binary"
   exec "$binary" "$@"
 else
   echo "error: buildifier sha mismatch" >&2
-  rm -f "$binary"
```
Comment (keith) [inline buildifier-wrapper.sh:68]: I think we still want to keep this removal? this is the case the binary is untrusted

Comment (Blaok) [reply buildifier-wrapper.sh]: Sure, reverted this part. Thanks for taking a look!

Comment (Blaok) [reply buildifier-wrapper.sh]: Emmmm, on second thought, it’s probably best to not `rm -f "$binary"`. Consider the following (unlikely but possible) scenario:

1. The wrapper is called when there is no existing binary.
2. While the binary is being downloaded, the wrapper is called again, which downloads the binary again (to a separate tmp file).
3. The first download succeeds and becomes $binary.
4. The second download fails. If we keep `rm -f "$binary"`, the good binary downloaded from the first run will be deleted, which leads to an unnecessary re-download in the future. The bad tmp binary from the second download will be removed on exit anyways, because of `trap 'rm -f "$tmp_binary"' EXIT`.

Comment (keith) [reply buildifier-wrapper.sh]: ++ removing tmp_binary is all that matters, sgtm

**Review by keith — APPROVED** [review]
